application: lumen-shop
version: 6
runtime: python
api_version: 1

derived_file_type:
- python_precompiled

inbound_services:
- mail

handlers:
- url: /(robots\.txt|favicon\.ico)
  static_files: static/\1
  upload: static/(.*)

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /img
  static_dir: static/img

- url: /tinymce
  static_dir: static/tinymce/jscripts/tiny_mce

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /_ah/queue/deferred
  script: main.py
  login: admin

- url: /.*
  script: main.py
